# Generated by Django 4.2.3 on 2023-07-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('count', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('time', models.TimeField()),
                ('earned_point', models.IntegerField()),
                ('cart_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer.customer')),
                ('cart_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='staff.staff')),
            ],
        ),
    ]
