# Generated by Django 4.2.3 on 2023-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('iban', models.IntegerField()),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
