# Generated by Django 4.2.3 on 2023-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
