# Generated by Django 4.2.3 on 2023-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('photo', models.ImageField(upload_to='media/img')),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
